function output = makeFancySpinString()
% Inspired by http://asciimator.net/asciimation/8276
output = ...
{...
'>           ', ...
' >          ', ...
'  >         ', ...
'  R>        ', ...
'  Ru>       ', ...
'  Run>      ', ...
'  Runn>     ', ...
'  Runni>    ', ...
'  Runnin>   ', ...
'  Running>  ', ...
'  Running.> ', ...
'  Running. >', ...
'  Running. )', ...
'  Running. |', ...
'  Running. (', ...
'  Running. <', ...
'  Running.< ', ...
'  Running<  ', ...
'  Runnin<   ', ...
'  Runni<    ', ...
'  Runn<     ', ...
'  Run<      ', ...
'  Ru<       ', ...
'  R<        ', ...
'  <         ', ...
' <          ', ...
'<           ', ...
'(           ', ...
'|           ', ...
')           '};

end